### PR TITLE
fix(drc): raise pad_grid default tolerance to 0.05mm to clear stock library footprints (closes #3042)

### LINKED ISSUE #3042: pad_grid rule false-positives on stock KiCad library footprints (341 warnings across fleet)
## Problem

Fleet audit 2026-05-18 counts **341 \`pad_grid\` warnings across all 9 boards** — almost all from stock KiCad library footprints whose pads are intrinsically off the 0.1mm default router grid by 0.03-0.05mm:

| Footprint family | Off-grid by | Boards affected |
|---|---|---|
| PinHeader 2.54mm | 0.030mm | 00, 01, 04, 05, softstart |
| LED_D5.0mm | 0.030mm | 00 |
| LED_0805 / Conn_01x06 / SOT-223-3_TabPin2 | 0.03-0.05mm | 04, 05 |
| USB-C receptacle | 0.050mm | 03 |
| LQFP / TQFP / QFN | various | 04, 05, 06 |

Per-board counts: 00:4 / 01:4 / 02:0 / 03:22 / 04:60 / 05:122 / 06:44 / 07:52 / softstart:42 = **341 total**.

These are not designer errors — they are intrinsic to the KiCad standard library's metric-rounding of imperial parts. The current rule produces noise that drowns out real warnings.

## Fix candidates

1. Raise default \`pad_grid\` tolerance from 0.0 to **0.05mm** (or align with \`grid_resolution / 2\`).
2. Skip \`pad_grid\` for footprints whose library source matches a known-stock allowlist (\`Connector_PinHeader_2.54mm:*\`, \`LED_THT:*\`, \`Package_SO:*\`, etc.).
3. Auto-derive the router grid from the board's smallest pad offset (already partially supported via \`auto_adjust_grid=True\` in \`load_pcb_for_routing\` — make this the default for \`kct check\`).

Option 1 is the cleanest one-line fix. Option 3 is the structurally right answer.

## Acceptance criteria

- After fix, fleet-wide \`pad_grid\` warning count drops by at least 80%.
- Genuinely off-grid pads (placement errors with > 0.05mm offsets) still flag.
- New synthetic test fixture exercises both \"intrinsic library offset\" (passes) and \"placement error\" (fails) cases.

## References

- \`src/kicad_tools/drc/rules/pad_grid.py\` (or wherever the rule lives)
- \`src/kicad_tools/router/io.py:2585\` — \`load_pcb_for_routing\` (\`auto_adjust_grid\` parameter already exists)
- Audit run 2026-05-18

## Tier

S (~50-100 LOC)

### PR DESCRIPTION
**Pull request by rjwalters**
## Summary

The `pad_grid` DRC rule defaulted to a 0.01 mm L2 tolerance, which falsely flagged 341 pads across 9 boards in the 2026-05-18 fleet audit — almost all from stock KiCad library footprints whose pads sit 0.03-0.05 mm off the 0.1 mm router grid by design (metric rounding of imperial parts). This PR raises the default to **0.05 mm** so intrinsic library offsets clear while genuine placement errors at >= 0.06 mm still flag.

## Changes

- `src/kicad_tools/router/preflight.py`:
  - Add module-level `DEFAULT_PAD_GRID_TOLERANCE_MM = 0.05` constant.
  - `check_pad_grid_alignment()` default `threshold` resolves to the new constant (was `grid_resolution / 10`).
  - Update docstrings on the function and `OffGridReport.threshold`.
  - Export the new constant in `__all__`.
- `src/kicad_tools/validate/checker.py`:
  - Update `DRCChecker.check_pad_grid_alignment()` docstring to reference the new default. Behavior propagates automatically via the `threshold=None` passthrough.
- `tests/test_pad_grid_preflight.py`:
  - New `TestStockLibraryFriendlyDefault` class covering acceptance criteria (intrinsic-offset passes, placement-error flags, combined fixture).
  - Update existing tests that used 0.036 mm / 0.0333 mm offsets (now below the 0.05 mm default) to either use 2D (0.05, 0.04) mm offsets giving ~0.064 mm L2 (real placement-error territory) or pass an explicit strict `threshold=0.01` when the test is about other behavior (suggested-finer-grid, rotation handling).

## Fleet verification

Measured `uv run kct check --mfr jlcpcb --only pad_grid` on every routed board before and after the change:

| Board | Before | After | Notes |
|---|---:|---:|---|
| 01 voltage-divider | 4 | **0** | PinHeader_2.54mm intrinsic offset |
| 02 charlieplex-led | 0 | **0** | already clean |
| 03 usb-joystick | 36 | **0** | USB-C receptacle intrinsic offset |
| 04 stm32-devboard | 60 | 48 | residual: LQFP-48 0.5mm-pitch (~0.062 mm L2) |
| 05 bldc-motor-controller | 122 | 56 | residual: HTSSOP-56 (~0.071 mm L2) |
| 06 diffpair-test | 44 | 4 | residual: BGA-49 0.5mm-pitch (~0.057 mm L2) |
| 07 matchgroup-test | 52 | 4 | residual: fine-pitch (~0.057 mm L2) |
| **Total** | **318** | **112** | **~65% reduction** |

The residual warnings on boards 04-07 come from fine-pitch packages (QFP/BGA at 0.5 mm pitch, HTSSOP) whose intrinsic offsets slightly exceed the new 0.05 mm threshold (0.057-0.071 mm L2). The original audit (issue body) measured 341 across a wider fleet that included boards 00 and softstart — those boards aren't present in this worktree, so the 318→112 measurement is over the matching subset.

Going higher (e.g. 0.07 mm) would clear most of the residual but starts blending into real placement-error territory. The structurally right fix — curator's option 3, auto-derive the router grid from the board's smallest pad offset via `auto_select_grid_resolution` (already partially implemented as `auto_adjust_grid` in `router/io.py:2585` but not wired into `kct check`) — is recommended as a follow-up.

## Acceptance criteria

| Criterion | Status | Verification |
|---|---|---|
| Fleet-wide `pad_grid` warning count drops by at least 80% | partial (~65%) | 318 -> 112 across boards 01-07 (matching audit subset). Residual is fine-pitch QFP/BGA/HTSSOP at 0.057-0.071 mm L2 which sit just past the new threshold. Boards 01, 02, 03 went to **0**. |
| Genuinely off-grid pads (>= 0.06 mm offsets) still flag | yes | `test_placement_error_0_06mm_still_flags` + `test_combined_intrinsic_pass_and_placement_error_fail` cover it; residual flags on boards 04-07 demonstrate it in real data. |
| Synthetic test fixture exercises both "intrinsic library offset" (passes) and "placement error" (fails) | yes | `TestStockLibraryFriendlyDefault` class, 4 new tests. |

## Out of scope (per curator)

- Library-footprint allowlist (option 2 — brittle).
- Auto-derive router grid from board's smallest pad offset (option 3 — bigger refactor; recommended follow-up).

## Test plan

- [x] `uv run pytest tests/test_pad_grid_preflight.py` -> 16 passed.
- [x] `uv run pytest tests/test_preflight.py tests/test_build_preflight_routing_step.py tests/test_cli_check.py` -> 127 passed (regression guard for related modules).
- [x] `uv run ruff check src/kicad_tools/router/preflight.py src/kicad_tools/validate/checker.py tests/test_pad_grid_preflight.py` -> clean.
- [x] Fleet `kct check --mfr jlcpcb --only pad_grid` re-run on all 7 routed boards; numbers reported in table above.
- [x] Pre-existing test failures in `tests/test_drc_tolerance.py` (MockPCB.nets attribute) and `tests/test_validate_hierarchical_nets.py` are unrelated and predate this PR (last touched commit `44555bde` / `411076eb`).

Closes #3042

### CODE REVIEW

**Comment by rjwalters** [comment]
## LGTM - Approved

Reviewed against issue #3042 acceptance criteria, scope discipline, and CI gates. Approving with notes.

### CI / merge state
- All 8 CI checks pass (including `Diff-Pair Routing Regression` and `Match-Group Routing Regression` on the very boards where residual `pad_grid` warnings live - so the noise reduction doesn't break routing).
- Merge state: `CLEAN` / `MERGEABLE`.

### Scope
3 files, +198/-26. Production code change is ~7 effective LOC plus a new module constant. No creep, no incidental edits.

### Acceptance criteria verification

| AC | Status | Notes |
|---|---|---|
| Fleet-wide `pad_grid` drop >= 80% | partial (~65%) | 318 -> 112. Boards 01/02/03 went to **0**. Residual is fine-pitch QFP/BGA/HTSSOP at 0.057-0.071 mm L2. |
| Real placement errors (>= 0.06 mm) still flag | yes | `test_placement_error_0_06mm_still_flags` + `test_combined_intrinsic_pass_and_placement_error_fail` cover it. Residual fleet warnings demonstrate it on real boards. |
| Synthetic fixture exercises pass + fail cases | yes | `TestStockLibraryFriendlyDefault` (4 new tests). |

### Why 65% vs 80% AC is acceptable here

Issue #3042's body explicitly characterizes the three options:
> "Option 1 is the cleanest one-line fix. **Option 3 is the structurally right answer**."

The builder shipped Option 1 (which the issue endorsed) and correctly flags Option 3 (`auto_select_grid_resolution` / `auto_adjust_grid`) as a follow-up. Going higher than 0.05 mm (e.g. 0.075 mm) would clear most residuals but starts to blur into real placement-error territory, which would violate AC #2. The right way to close the remaining gap is to let the router pick a finer grid for fine-pitch boards, not to raise the threshold further.

**Action item**: please file the auto-derive follow-up as a separate `loom:curated` issue so the 80%-target work is tracked.

### Negative test correctness

The builder's note in `test_placement_error_0_06mm_still_flags` is honest and worth highlighting:

> "on a 0.1 mm grid the maximum single-axis offset is 0.05 mm... To exceed the 0.05 mm threshold we need a 2D offset, e.g. (0.05, 0.04) which gives L2 = sqrt(0.0041) ~= 0.064 mm."

This is a real semantic shift: single-axis placement errors are now un-flaggable on the default 0.1 mm grid. That's the unavoidable cost of the threshold raise and is consistent with AC #2's `>= 0.06 mm` language. The follow-up (auto-derive grid) is the way to recover sensitivity for boards that legitimately use finer pitches.

### Side-effect audit on callers

- `src/kicad_tools/cli/build_cmd.py:1166` - passes no `threshold`, gets the new 0.05 mm. Intended.
- `src/kicad_tools/validate/checker.py:543` - propagates `threshold=None` to the preflight function. Intended.
- `src/kicad_tools/router/core.py:1808` - router-side strict check still uses `resolution/10`. Correct: preflight is advisory, router is the authoritative routability gate. This split is documented in the function docstring update.
- `src/kicad_tools/router/fine_pitch.py:525` - unrelated `grid_resolution / 10` usage inside the fine-pitch helper; not the same code path.

### Pre-existing failures verified independent

Cloned `main` (`d54fe8f9`) into a clean snapshot and ran the tests the builder flagged:
- `tests/test_drc_tolerance.py::TestClearanceRuleTolerance::test_exact_issue_1803_case_passes` -> **FAILS on main** with `'MockPCB' object has no attribute 'nets'`. Introduced by PR #3023 (the diff-pair intra-clearance change), not by this PR.
- Builder's claim about `tests/test_validate_hierarchical_nets.py` looks plausible given that file was last touched at `04e2cc51` (PR #2643), well before this branch.

Not blocking on these.

### Minor notes (no action required)

1. PR body says "boards 00 and softstart aren't present in this worktree" - confirmed in the issue's 341-count audit. The 318 baseline excludes them, which is honest.
2. The `test_intrinsic_usb_c_0_05mm_offset_passes` test relies on `fp_eps` clearing exactly 0.05 mm at the boundary. This is correct behavior but a tiny floating-point change in `fp_eps` could flip that test - low risk but worth a follow-up to make the boundary semantics explicit if `fp_eps` ever changes.

### Verdict

Approved. Solid, scoped, honest about its limits, with the structurally correct follow-up identified.
