### PR TITLE
fix(ci): Test job gates on pytest exit — burn down masked failures (closes #3436)

### LINKED ISSUE #3436: CI Test job masks all test failures: continue-on-error true hides 162 failed + 30 errors on main
## Problem

The `Test` job in `.github/workflows/ci.yml` (line 71) runs:

```yaml
- name: Run tests
  run: uv run pytest -n auto -o addopts= --benchmark-disable --timeout=60 -m "not slow"
  continue-on-error: true
```

`continue-on-error: true` makes the job green **regardless of test results**. CI run 27242706499-era main (run 27235563106, commit 3dc88588) shows:

```
= 162 failed, 18675 passed, 340 skipped, 1 xfailed, 193 warnings, 30 errors in 543.04s =
```

…and the job still reported success. This caused the #3427 "local-vs-CI divergence" investigation: the two fine-pitch tests were failing in CI all along (since PR #2866, 2026-05-13), but the green checkmark hid it. **Any** new test regression is currently invisible to CI, Judges, and the merge queue.

The Lint & Format job appears similarly masked (`Would reformat:` output on green runs).

## Failure categories observed on main (run 27235563106)

- `FileNotFoundError: Library not found: Comparator.kicad_sym / Device.kicad_sym` (environment: KiCad symbol libraries absent on CI runner) — many tests
- `MockPCB object has no attribute 'nets'` (test_drc_tolerance.py — stale mock)
- pytest-timeout 60s kills (test_diffpair_npad.py etc.)
- Assorted stale assertions (test_fine_pitch_clearance.py — fixed in PR for #3427, test_cli_sch.py, test_diffpair_length_tuning.py, …)
- 30 collection/setup errors

## Suggested approach

1. Triage the 162 failures + 30 errors into: environment-dependent (needs skip-if-missing guard or CI fixture install), stale tests (update), real defects (fix or file).
2. Burn the list down to zero (possibly via a tracking issue with sub-issues per category).
3. Remove `continue-on-error: true` from the Test step so CI is load-bearing again.
4. Consider the same for the Lint & Format and mypy steps.

## Acceptance

- `continue-on-error: true` removed from the Test step
- CI Test job is red iff tests fail

Discovered while implementing #3427.

### PR DESCRIPTION
**Pull request by rjwalters**
Closes #3436

## Summary

The CI Test job had `continue-on-error: true` — green regardless of pytest's exit code. When #3436 was filed, main carried **162 failed + 30 errors** (163+21 on the latest main run before this PR). This PR removes the mask and burns the failure list down to **zero**:

```
19459 passed, 97 skipped, 19 xfailed, 0 failed — exit 0
```
(full local run of the exact CI invocation: `pytest -n auto -o addopts= --benchmark-disable --timeout=60 -m "not slow"`)

### CI workflow (`.github/workflows/ci.yml`)
- **Removed `continue-on-error` from the Test step** — the job now gates.
- Test job now runs inside the `kicad/kicad:10.0` container (same image as the kicad-cli smoke job): provides KiCad-10 symbol/footprint libraries and kicad-cli 10 (fixes the ~51-failure "Library not found: Device.kicad_sym" class plus the KiCad-7-era apt-library failures — environmental, the code was fine).
- Build the C++ router backend before the run (`uv sync` does not); kills the 60s-timeout failure class caused by pure-Python fallback.
- Lint & mypy steps keep `continue-on-error` with inline annotations pointing at their own burn-down issues (#3464, #3512 — out of scope here).

### Real product bugs the gate was hiding (fixed)
- `pipeline_cmd.py`: **duplicate `_run_step_fix_erc` definition** (parallel PRs #1378/#1379); the shadowing copy dropped the "skip when zero ERC errors" gate. Deleted. Also `layer_count` now coerces int `layers`.
- `router/adaptive.py`: `_create_autorouter` used an `Autorouter.__new__` bypass with a hand-maintained attribute list that rotted (`_use_waypoint_injection`, `_matrix_conflict_nets` missing → AttributeError on the hierarchical/adaptive path). Replaced with a real `__init__` call.

### Stale tests updated (~35 tests, see commit 09f00228 for the full list)
Highlights: report auto-collection/`--skip-collect`, REPORT step `manufacturing/` output dir, JLCPCB 4-layer annular ring 0.10mm (#1414), SOIC-8 dense band (#3398), route exit codes 2–5 non-fatal, CCW-positive rotation convention (#738/#2129), `export_gerbers` zip output, board-02 deterministic baseline re-pinned after #3203/#3510 (fewer segments, same routes/vias/reach).

### xfail with tracking issues (19 tests, all `strict=False` + issue link)
- #3445 route_zones_preserved source-shape guards (2)
- #3490 route_to_pad_adjacent_to_net0_pad (1)
- #3492 softstart call-site guard (1)
- #3518 rotation-convention hand-drawn fixtures — net extraction (5)
- #3519 charlieplex bare `route_all()` completion regression (1)
- #3520 TestTryPreloadCairoMacos stale vs preload rewrite (2)
- #3521 board-05 sync-drift fixture rot (3)
- #3522 RtreeSegmentIndex inf-clearance parity **(real defect)** (1)
- #3524 diffpair xdist state-pollution + Python coupled A* timeout (2)
- 1 pre-existing xfail

### Robustness
Heavy board-routing modules get `pytest.mark.timeout(300–900)` overrides so the xdist CPU-contention reaper stops killing them spuriously at the CLI default of 60s (this was a major CI-only failure class).

## Test plan
- [x] Full CI invocation locally (3 consecutive runs): final run 19459 passed / 0 failed / exit 0
- [x] All xfails verified to carry a tracking-issue link; xpass allowed (strict=False)
- [x] Per-file ruff parity vs main (no new lint errors in touched files)
- [ ] CI Test job on this PR goes green WITH the gate live (the real acceptance test)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by rjwalters** [comment]
CI status note for reviewers:

- **Test job (the acceptance criterion of #3436): PASS with the gate live** — `19,46x passed, 19 xfailed, 0 failed` in the kicad/kicad:10.0 container, exit code now load-bearing.
- **Match-Group Routing Regression: red, but NOT from this PR.** The job fails identically on main itself at 9b16ea65 (29 DRC errors vs allowlist 28) — tracked by #3533. This PR's rounds 1-2 (merge refs against older main) passed the job twice; round 3 inherits the main-side regression via the merge ref. No file in this PR touches the board-07 routing path.

Burn-down evidence: three failure classes were CI-environment (KiCad-7-era apt libraries, missing kicad-cli, xdist contention timeouts) and are fixed in the workflow itself; the rest were stale tests (fixed), real product bugs (fixed: duplicate `_run_step_fix_erc`, AdaptiveAutorouter `__new__` attribute rot), or xfailed with tracking issues (#3445 #3490 #3492 #3518 #3519 #3520 #3521 #3522 #3524).

**Comment by rjwalters** [comment]
✅ **Approved!**

This is the keystone PR of the CI campaign: the Test job now actually gates, and the 162-failed/30-error backlog it was hiding is burned down to zero with the gate live on this PR's own run (Test: pass, 13m18s).

## Verification performed

**1. Container switch (`kicad/kicad:10.0`)** — Sound and consistent. The image is pinned by `10.0` tag, identical to the pre-existing kicad-cli-smoke job (which set the precedent and is explicitly cross-referenced in the new job's comments: `--user 0:0`, bash-over-dash, curl-installed uv instead of `setup-uv@v4`). Tag-not-digest matches the smoke job's existing convention; `10.0` tracks patch releases only. The routing-regression jobs (Match-Group, Diff-Pair, DRC check) are untouched — they route existing boards and don't need symbol libraries, confirmed by their green runs here. Pull + apt prerequisites + native build still land the job at 13m18s, well inside the 45-min timeout. The `--python 3.12` pin via uv preserves interpreter parity with the other jobs.

**2. Product bug 1 — `pipeline_cmd.py` duplicate `_run_step_fix_erc`** — Verified the correct copy survives. The deleted definition (formerly ~line 667) was defined *after* the surviving one (line 580) so it shadowed it at import time, and it lacked the zero-error skip gate. The surviving implementation has the gate live: skips when `ctx.erc_error_count == 0 and not ctx.force`, plus the no-schematic skip and dry-run path. Only one definition + one STEP_RUNNERS binding remain. The `_layer_count` `str()` coercion for int `layers` is a sensible companion fix.

**3. Product bug 2 — `AdaptiveAutorouter.__new__` bypass (this is #3484's defect)** — Verified fixed, and it implements #3484's *preferred* fix (eliminate the bypass entirely, not the stopgap). I ran #3484's exact reproduction on this branch: `ar.use_waypoint_injection` resolves, `_matrix_conflict_nets` is present, `_run_subgrid_prepass()` succeeds, and a full `AdaptiveAutorouter.route()` completes (RoutingResult, CONVERGED). **#3484's acceptance criteria are met — it should be closed when this merges.** Note the PR trailer only closes #3436, so #3484 needs manual closure by the orchestrator.

**4. xfail spot-check (3 of 18)** — All carry tracking links; the issues genuinely describe the failures:
- **#3518** (5 rotation-fixture tests): detailed root cause (rotate-then-negate vs negate-then-rotate, refs #738/#2129), names all 5 tests with exact assertion deltas, and explains why fixture redraw was deferred. Accurate.
- **#3522** (rtree parity): correctly flagged as a REAL production defect (clearance=inf vs brute-force 3.33mm → DRC can miss violations), not test rot. Accurate and appropriately severe.
- **#3524** (diffpair xdist pollution + Python coupled-A* timeout): env-dependent by nature; `strict=False` is unambiguously correct here.

On strict-ness: the split is uniform `strict=False` rather than per-case. For env/timing-dependent cases (#3524, #3521, #3519, #3490) that's right. For the deterministic ones (#3518, #3520, #3445, #3492, #3522) `strict=True` would give tripwire semantics per the #3420 precedent — but in the PR that turns the gate ON, uniform non-strict is the conservative choice (an unexpected xpass must not redden the brand-new gate), and every tracking issue explicitly instructs removing the mark on fix, which covers the tripwire role. Acceptable as-is; recommend flipping deterministic ones to strict when their fixes land.

**5. Timeout overrides** — Verified per-module `pytestmark = pytest.mark.timeout(300|600|900)` declarations only; the CLI default stays 60s for the rest of the suite. Every override carries the same documenting comment (xdist CPU-contention reaper, does not slow the happy path). Not masking product slowness — these are real-board routing/generation modules.

**6. Local verification** — C++ backend confirmed available in the worktree; scoped runs on the touched modules: `test_pipeline_cmd + test_rtree_segment_index + test_adaptive_early_stop + test_best_state_tracking + test_negotiated_timeout_propagation` → 314 passed, 1 xfailed; `test_router_core + test_cli_netlist + test_netlist_query + test_validate_hierarchical_nets + test_sch_pin_map + test_mcp_screenshot` → 345 passed, 11 skipped, 8 xfailed. No xpasses. Diff hygiene clean (no pycache/.so artifacts; the accidental commit was reverted in c2a47cf7).

**CI status** — 7/8 green. The single red (Match-Group, 29 vs 28) is main-inherited: identical failure on main run 27373868262 and on unrelated PR #3526, tracked in #3533 with a fix in flight. Not attributable to this PR (which passed that job twice before main moved). `mergeStateStatus: UNSTABLE` is acceptable under these facts.

**Fixed during evaluation**: updated one stale PR-body bullet that still described the abandoned apt-install approach; the body now reflects the container approach actually shipped.

**For the orchestrator**: close #3484 manually after merge (trailer only lists #3436).
