### ISSUE TITLE
CI Test job masks all test failures: continue-on-error true hides 162 failed + 30 errors on main

### ISSUE THREAD

**Issue by rjwalters** [rjwalters/kicad-tools#3436]
## Problem

The `Test` job in `.github/workflows/ci.yml` (line 71) runs:

```yaml
- name: Run tests
  run: uv run pytest -n auto -o addopts= --benchmark-disable --timeout=60 -m "not slow"
  continue-on-error: true
```

`continue-on-error: true` makes the job green **regardless of test results**. CI run 27242706499-era main (run 27235563106, commit 3dc88588) shows:

```
= 162 failed, 18675 passed, 340 skipped, 1 xfailed, 193 warnings, 30 errors in 543.04s =
```

…and the job still reported success. This caused the #3427 "local-vs-CI divergence" investigation: the two fine-pitch tests were failing in CI all along (since PR #2866, 2026-05-13), but the green checkmark hid it. **Any** new test regression is currently invisible to CI, Judges, and the merge queue.

The Lint & Format job appears similarly masked (`Would reformat:` output on green runs).

## Failure categories observed on main (run 27235563106)

- `FileNotFoundError: Library not found: Comparator.kicad_sym / Device.kicad_sym` (environment: KiCad symbol libraries absent on CI runner) — many tests
- `MockPCB object has no attribute 'nets'` (test_drc_tolerance.py — stale mock)
- pytest-timeout 60s kills (test_diffpair_npad.py etc.)
- Assorted stale assertions (test_fine_pitch_clearance.py — fixed in PR for #3427, test_cli_sch.py, test_diffpair_length_tuning.py, …)
- 30 collection/setup errors

## Suggested approach

1. Triage the 162 failures + 30 errors into: environment-dependent (needs skip-if-missing guard or CI fixture install), stale tests (update), real defects (fix or file).
2. Burn the list down to zero (possibly via a tracking issue with sub-issues per category).
3. Remove `continue-on-error: true` from the Test step so CI is load-bearing again.
4. Consider the same for the Lint & Format and mypy steps.

## Acceptance

- `continue-on-error: true` removed from the Test step
- CI Test job is red iff tests fail

Discovered while implementing #3427.
